Cargo audit, remove vulnerable crate imageproc.
After running `cargo audit`, it turns out `imageproc` crate has a known vulnerability:
https://rustsec.org/advisories/RUSTSEC-2020-0023

Also, we're no longer using anything from this crate.
If we need something in the future, keep an eye on this pull request that
seems to solve the issue by swapping the vulnerable dependency in imageproc
with another crate:
https://github.com/image-rs/imageproc/pull/417

Details:

```
$cargo audit

error: Vulnerable crates found!

ID:       RUSTSEC-2020-0023
Crate:    rulinalg
Version:  0.4.2
Date:     2020-02-11
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0023
Title:    Lifetime boundary for `raw_slice` and `raw_slice_mut` are incorrect
Solution:  No safe upgrade is available!
Dependency tree:
rulinalg 0.4.2
└── imageproc 0.21.0
    └── noaa-apt 1.2.0
```